version: "3.9"

services:
  ansible:
    image: alpine/ansible
    container_name: ansible-playbook
    user: root
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_GALAXY_CMD=ansible-galaxy collection install --force community.
    volumes:
      - "./playbook:/playbook"      
      - "./services:/opt/fhir-patrick"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: /playbook
    stdin_open: true
    tty: true
    command: >
      sh -c "
        apk add --no-cache py3-pip git docker-cli &&
        pip install --break-system-packages requests docker &&
        ansible-galaxy collection install --force community.docker &&
        ansible-playbook -i inventories/local.yml playbook.yml
      "
    networks:
      - fhir-network
networks:
  fhir-network:
    driver: bridge